# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use docker login
      - name: Docker Hub login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Build and push the image to Container Registry
      - name: Build and Push container to registry
        run: |
          docker build --file=taskapp/taskapp/Dockerfile -t sorenmaagaard/cuda-10.2-windows-ci:${{ github.sha }} .
          docker push sorenmaagaard/cuda-10.2-windows-ci:${{ github.sha }}
      - name: Push container to registry as latest
        if: ${{ github.ref == 'ref/head/master' }}
        run: |
          docker tag sorenmaagaard/cuda-10.2-windows-ci:${{ github.sha }} sorenmaagaard/cuda-10.2-windows-ci:latest
          docker push sorenmaagaard/cuda-10.2-windows-ci:latest
          
